name: Release

on:
  workflow_run:
    workflows: ["Release Check"]
    types: [completed]
    branches: [main]

permissions:
  id-token: write
  contents: write
  pull-requests: write
  issues: write
  actions: read

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create a Release
        id: create-release
        uses: ./.github/actions/release
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

  release-fail:
    name: Complete
    needs: ['release']
    runs-on: ubuntu-latest
    if: always() && needs.release.result != 'success'
    environment:
      name: test
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Comment on Issue
        id: comment
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: "Failed to create a Release",
              body: "The pipeline has failed to create a Release.  This means the code on the main branch has not been deployed and not passed the testing",
              labels: ['Failed Release', 'Test/Production']
            core.setFailed('Release FAILED - Release Required')
