name: Version

on:
  pull_request:
    branches:
      - main


permissions:
  id-token: write
  contents: write
  pull-requests: write
  actions: read

jobs:
  main-version:
    name: Main Version
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.package-version.outputs.result }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          ref: main
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Get Version
        id: package-version
        uses: actions/github-script@v6
        with:
          result-encoding: string
          script: return require('./package.json').version

      - name: Version
        run: echo ${{ steps.package-version.outputs.result }}

  pr-version:
    name: PR Version
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.package-version.outputs.result }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Get Version
        id: package-version
        uses: actions/github-script@v6
        with:
          result-encoding: string
          script: return require('./package.json').version

      - name: Version
        run: echo ${{ steps.package-version.outputs.result }}

  merge:
    name: Merge
    runs-on: ubuntu-latest
    needs: ['pr-version', 'main-version']
    if: ${{ needs.pr-version.outputs.version < needs.main-version.outputs.version }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Merge main
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "${{ github.actor }}"
          git status
          git pull
          git checkout main
          git status
          git checkout "$GITHUB_HEAD_REF"
          git merge main --no-edit
          git push
          git status

      - name: Upgrade Version
        uses:  ./.github/actions/upgrade-version
        with:
          github-user: ${{ github.actor }}

      - name: Push Version
        shell: bash
        run: git push

  update:
    name: Update Version
    runs-on: ubuntu-latest
    needs: ['pr-version', 'main-version']
    if: ${{ needs.pr-version.outputs.version == needs.main-version.outputs.version }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Branch
        shell: bash
        run: git checkout "$GITHUB_HEAD_REF"

      - name: Upgrade Version
        uses:  ./.github/actions/upgrade-version
        with:
          github-user: ${{ github.actor }}

      - name: Push version
        shell: bash
        run: git push

      - name: Get Version
        id: package-version
        uses: actions/github-script@v6
        with:
          result-encoding: string
          script: return require('./package.json').version

      - name: Version
        run: echo ${{ steps.package-version.outputs.result }}

  complete-version:
    name: Complete Version
    runs-on: ubuntu-latest
    needs: ['update', 'merge']
    if:  always()
    steps:
      - name: Complete Version update
        shell: bash
        run: echo "Complete"
